name: Vividus Advance Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Execute at 24:00 UTC+7 Monday to Friday
    - cron: '0 0 * * 1-5'

jobs:
  build:
    runs-on: windows-latest
    name: Build and Run tests
    
    steps:
    - name: Checkout (including submodules and tags) 
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Set up JDK 19
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '19'
        distribution: 'temurin'
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
  
    - name: Run tests
      run: ./gradlew runStories

    # - name: Upload artifact
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: allure-results
    #     path: output/allure-results
  
  generate_report:
    name: Generate Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ build ]
    steps:
    # - name: Download Artifacts ðŸ”»
    #   uses: actions/download-artifact@v4
    #   id: download
    #   with:
    #     name: allure-results
    #     path: allure-results
    
    - name: Get Allure history
      uses: actions/checkout@v4.1.1
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report with history
      uses: simple-elf/allure-report-action@v1.8
      if: always()
      id: allure-report
      with:
        allure_results: output/allure-results
        allure_history: allure-history
        keep_reports: 30

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: always()
      with:
        personal_token: ${{ secrets.ACTION_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
